app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('categories', views.categories, name='categories'),
    path('marcas', views.brands, name='brands'),
    path('produtos', views.products, name='products')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models
from distutils.command.upload import upload

class Category(models.Model):
    title=models.CharField(max_length=180)
    image=models.ImageField(upload_to='products/')

    def __str__(self):
        return self.title

class Marca(models.Model):
    title=models.CharField(max_length=180)
    image = models.ImageField(upload_to='marca_imgs/', null=True, blank=True)

    def __str__(self):
        return self.title

class Color(models.Model):
    title=models.CharField(max_length=100)
    color=models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Size(models.Model):
    title=models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Product(models.Model):
    title=models.CharField(max_length=200)
    image=models.ImageField(upload_to='products_imgs/')
    slug=models.CharField(max_length=200)
    detail=models.TextField()
    specs=models.TextField()
    marca=models.ForeignKey(Marca, on_delete=models.CASCADE)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    size=models.ForeignKey(Size, on_delete=models.CASCADE)
    color=models.ForeignKey(Color, on_delete=models.CASCADE)
    status=models.BooleanField(default=True)
    fav=models.BooleanField(default=False)

    def is_fav(self):
        if self.fav==True:
            self.status=False
        return Product

    def __str__(self):
        return self.title

class ProductAttribute(models.Model):
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    color=models.ForeignKey(Color, on_delete=models.CASCADE)
    size=models.ForeignKey(Size, on_delete=models.CASCADE)
    price=models.PositiveIntegerField()

    def __str__(self):
        return self.product.title

class Banner(models.Model):
    img=models.CharField(max_length=250)
    alt_text=models.CharField(max_length=300)

app/views.py
from django.shortcuts import render
from .models import *


def home(request):
    favs = Product.objects.filter(fav=True).order_by('-id')
    return render(request,'index.html', {'favs':favs})

def categories(request):
    data=Category.objects.all().order_by('-id')
    return render(request, 'categories.html', {'data':data})

def brands(request):
    data=Marca.objects.all().order_by('-id')
    return render(request, 'brands.html', {'data':data})

def products(request):
    data=Product.objects.all().order_by('-id')
    cat=Product.objects.distinct().values('category__title', 'category__id')
    brand=Product.objects.distinct().values('marca__title', 'marca__id')
    color=ProductAttribute.objects.distinct().values('color__title', 'color__color')
    size=ProductAttribute.objects.distinct().values('size__title', 'size__id')
    return render(request, 'products_list.html',
    {
        'data':data,
        'cats':cat,
        'brands':brand,
        'sizes':size,
        'colors':color,
    })

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Loja com Django</title>
	<!-- Font Awesome -->
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
	<!-- Bootstrap 4 CSS -->
	  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<!-- Main Jquery -->
	<script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
	<!-- Bootstrap 4 JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<!-- CustomJs -->
	<link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" />
	<script type="text/javascript" src="{% static 'custom.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container">
		  <a class="navbar-brand" href="/">Loja com Django</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNav">
		  	<form class="form-inline my-2 my-lg-0" action="/search">
		      <div class="input-group">
				  <input name="q" type="text" class="form-control" placeholder="Pesquisar" />
				  <div class="input-group-append">
				    <button class="btn btn-dark" type="submit" id="button-addon2">Pesquisar</button>
				  </div>
				</div>
		    </form>
		    <ul class="navbar-nav ml-auto">
		      <li class="nav-item">
		        <a class="nav-link text-white" href="/">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'categories' %}">Categorias</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href="{% url 'brands' %}">Marcas</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link text-white" href=""><i class="fa fa-shopping-cart"></i> Carrinho (<span class="cart-list"></span>)</a>
		      </li>
		      <li class="nav-item dropdown">
		        <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          <i class="fa fa-user"></i> Minha Conta
		        </a>
		        <div class="dropdown-menu" aria-labelledby="navbarDropdown">

		        	<a class="dropdown-item" href="">Painel</a>
		        	<a class="dropdown-item" href="">Sair</a>

	        		<a class="dropdown-item" href="">Login</a>
		          <a class="dropdown-item" href="">Cadastrar</a>

		        </div>
		      </li>
		    </ul>
		  </div>
		</div>
    </nav>

    {% block content %}
    {% endblock %}

</body>
</html>

app/templates/brands.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">

	<h3 class="my-4 border-bottom pb-1">Marcas</h3>
	<div class="row">
		{% if data %}
			{% for brand in data %}
				<div class="col-md-3 mb-4">
					<div style="height: 100%; width: 100%" class="card shadow">
					<a href=""><img src="/media/{{brand.image}}" class="card-img-top" alt="{{brand.title}}" /></a>
					<div class="card-body">
						<h6 class="card-text"><a href="#">{{brand.title}}</a></h6>
					</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

app/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">

	<h3 class="my-4 border-bottom pb-1">Categorias</h3>
	<div class="row">
		{% if data %}
			{% for cat in data %}
				<div class="col-md-3 mb-4">
					<div class="card shadow">
					<a href=""><img src="/media/{{cat.image}}" class="card-img-top" alt="{{cat.title}}" /></a>
					<div class="card-body">
						<h6 class="card-text"><a href="#">{{cat.title}}</a></h6>
					</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
</main>
{% endblock %}

app/templates/filters.html
{% load static %}
<script type="text/javascript" src="{% static 'product-filter.js' %}"></script>
			<h3 class="mb-4 border-bottom pb-1">Filtros</h3>
			
			<div class="card mb-4">
				<h6 class="card-header">Preco</h6>
				<div class="list-group list-group-flush">
					<li class="list-group-item">
						<input type="range" value="{{minMaxPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} id="rangeInput" oninput="maxPrice.value=this.value" />
						<p>{{minMaxPrice.price__min}}-{{minMaxPrice.price__max}}</p>
					</li>
					<li class="list-group-item">
						Maximo: <input type="number" value="{{minMaxPrice.price__min}}" max={{minMaxPrice.price__max}} min={{minMaxPrice.price__min}} class="form-control" id="maxPrice" onkeyup="rangeInput.value=this.value" id="maxPrice" />
						<button id="priceFilterBtn" class="btn btn-info btn-sm mt-1">Filtros</button>
					</li>
				</div>
			</div>
			
			<div class="card mb-4">
				<h6 class="card-header">Cores</h6>
				<div class="list-group list-group-flush">
					{% for color in colors %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="color" value="{{color.color__id}}" type="checkbox" />&nbsp;
						<button class="btn" style="background-color: {{color.color__color}}; margin-top: -5px;"></button>
					</li>
					{% endfor %}
				</div>
			</div>
		
			<div class="card mb-4">
				<h6 class="card-header">Categorias</h6>
				<div class="list-group list-group-flush">
					{% for cat in cats %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="category" value="{{cat.category__id}}" type="checkbox" />&nbsp;
						{{cat.category__title}}
					</li>
					{% endfor %}
				</div>
			</div>
		
			<div class="card mb-4">
				<h6 class="card-header">Marcas</h6>
				<div class="list-group list-group-flush">
					{% for marca in brands %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="marca" value="{{marca.marca__id}}" type="checkbox" />&nbsp;
						{{marca.marca__title}}
					</li>
					{% endfor %}
				</div>
			</div>
			
			<div class="card mb-4">
				<h6 class="card-header">Tamanhos</h6>
				<div class="list-group list-group-flush">
					{% for size in sizes %}
					<li class="list-group-item">
						<input class="filter-checkbox" data-filter="size" value="{{size.size__id}}" type="checkbox" />&nbsp;
						{{size.size__title}}
					</li>
					{% endfor %}
				</div>
			</div>

app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">

    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>

    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>

  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static '/media/images/banners/banner-1.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static '/media/images/banners/banner-1.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static '/media/images/banners/banner-1.jpg' %}" class="d-block w-100" alt="...">
    </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Proximo</span>
  </a>
</div>
</div>
<main class="container my-4">
	<h3 class="my-4 border-bottom pb-1">Produtos Em Destaques</h3>
	<div class="row">

		<div class="col-md-3 mb-4">
            {% for product in favs %}
                    <div class="card shadow">
                      <a href="/product/{{product.slug}}/{{product.id}}"><img  style="width: 100%; height: 100%" src="/media/{{product.image}}" class="card-img-top" alt="{{product.title}}"></a>
                      <div class="card-body" >
                        <h5 class="card-text"><a href=""></a>{{product.title}}</h5>
                  <h6>R$ <span class=""></span></h6>
                      </div>
                      <div class="card-footer">

                  <input type="hidden" value="1" class="form-control product-qty-{{product.id}}" id="productQty" />
                  <input type="hidden" class="product-image-{{product.id}}" value="{{product.productattribute_set.first.image}}" />
                  <input type="hidden" class="product-id-{{product.id}}" value="{{product.id}}" />
                  <input type="hidden" class="product-title-{{product.id}}" value="{{product.title}}" />
                        <button class="btn btn-sm btn-primary add-to-cart" data-index="{{product.id}}"><i class="fa fa-shopping-cart"></i></button>

                        <button class="btn btn-sm btn-danger add-wishlist" data-product="{{product.id}}"><i class="fa fa-heart"></i></button>

                  <button class="btn btn-sm btn-danger disabled"><i class="fa fa-heart"></i></button>

                        <span class="float-right">
                            4.5/5
                            <i class="fa fa-star text-warning"></i>
                        </span>
                      </div>
                    </div>
                </div>
            {% endfor %}
	</div>
    <p class="my-4 text-center"><a href="{% url 'products' %}" class="btn btn-dark btn-sm">Ver Todos os Produtos</a></p>
</main>
{% endblock %}

app/templates/products_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">

			<h3 class="mb-4 border-bottom pb-1">
				Produtos
			</h3>
			<div class="row" id="filteredProducts">
				{% for product in data %}
				{% if product.status == True %}
					<div class="col-lg-4 col-md-6 mb-4 product-box">
					<div class="card shadow" style="height: 100%; width: 100%">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>$ <span class="</span></h6>
					  </div>
					  	<div class="card-footer">

							  	<button class="btn btn-sm btn-primary add-to-cart" data-index=""><i class="fa fa-shopping-cart"></i></button>
							  	<button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
							  	<span class="float-right">
							  		4.5/5
							  		<i class="fa fa-star text-warning"></i>
							  	</span>
					  	</div>
					</div>
				</div>
				{% endif %}
				{% endfor %}
			</div>
			<p class="my-4 text-center"><button id="loadMore" data-total="" data-limit="3" class="btn btn-dark btn-sm">Carregar + <i class="fa fa-sync load-more-icon"></i></button></p>
		</div>
	</div>
</main>
{% endblock %}